import express from 'express';

import { isAuthenticated } from '../../middlewares/isAuthenticated.js';
import { isAdmin } from '../../middlewares/isAdmin.js';
import { isAdminOrReadOnly } from '../../middlewares/isAdminOrReadOnly.js';

import { Employees } from '../../controllers/employees/index.js';
import { ENDPOINTS } from '../endpoints.js';

import { upload } from '../../helpers/multer.js';

export const employeeRouter = express.Router();

// GET ---------------------------
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEES,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employees,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeById,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_DOCS,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeDocs,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_HISTORY,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeHistory,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_ABSENCES,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeAbsences,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_LICENSES,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeLicenses,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_VACATIONS,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeVacations,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_TRAININGS,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeTrainings,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_FORMAL_WARNINGS,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeFormalWarnings,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_EXTRA_HOURS,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeLateArrivals,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_LATE_ARRIVALS,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.employeeExtraHours,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_EMPLOYEE_FAMILY_MEMBER,
  isAuthenticated,
  isAdmin,
  Employees.GetController.employeeFamilyMember,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_LICENSES_TYPES,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.licensesTypes,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_LICENSE_TYPE,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.licensesTypesById,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_TRAINING_TYPES,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.trainingsTypes,
);
employeeRouter.get(
  ENDPOINTS.EMPLOYEES.GET_TRAINING_TYPE,
  isAuthenticated,
  isAdminOrReadOnly,
  Employees.GetController.trainingsTypesById,
);

// POST ---------------------------
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE,
  isAuthenticated,
  isAdmin,
  upload.single('imgFile'),
  Employees.PostController.createEmployee,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_DOC,
  isAuthenticated,
  isAdmin,
  upload.single('file'),
  Employees.PostController.createEmployeeDoc,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_ABSENCE,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createEmployeeAbsence,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_LICENSE,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createEmployeeLicense,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_VACATION,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createEmployeeVacation,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_TRAINING,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createEmployeeTraining,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_FORMAL_WARNING,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createEmployeeFormalWarning,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_EXTRA_HOUR,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createEmployeeLateArrival,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_LATE_ARRIVAL,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createEmployeeExtraHour,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_EMPLOYEE_FAMILY_MEMBER,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createFamilyMember,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_LICENSE_TYPE,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createLicenseType,
);
employeeRouter.post(
  ENDPOINTS.EMPLOYEES.POST_TRAINING_TYPE,
  isAuthenticated,
  isAdmin,
  Employees.PostController.createTrainingType,
);

// PUT ----------------------------
employeeRouter.put(
  ENDPOINTS.EMPLOYEES.PUT_EMPLOYEE,
  isAuthenticated,
  isAdmin,
  Employees.PutController.updateEmployee,
);
employeeRouter.put(
  ENDPOINTS.EMPLOYEES.PUT_EMPLOYEE_IMAGE,
  isAuthenticated,
  isAdmin,
  upload.single('imgFile'),
  Employees.PutController.updateEmployeeImage,
);
employeeRouter.put(
  ENDPOINTS.EMPLOYEES.PUT_EMPLOYEE_DOC,
  isAuthenticated,
  isAdmin,
  Employees.PutController.updateEmployeeDoc,
);
employeeRouter.put(
  ENDPOINTS.EMPLOYEES.PUT_EMPLOYEE_FAMILY_MEMBER,
  isAuthenticated,
  isAdmin,
  Employees.PutController.updateEmployeeFamilyMember,
);
employeeRouter.put(
  ENDPOINTS.EMPLOYEES.PUT_LICENSE_TYPE,
  isAuthenticated,
  isAdmin,
  Employees.PutController.updateLicenseType,
);
employeeRouter.put(
  ENDPOINTS.EMPLOYEES.PUT_TRAINING_TYPE,
  isAuthenticated,
  isAdmin,
  Employees.PutController.updateTrainingType,
);

// DELETE -------------------------
employeeRouter.delete(
  ENDPOINTS.EMPLOYEES.DELETE_EMPLOYEE,
  isAuthenticated,
  isAdmin,
  Employees.DeleteController.deleteEmployee,
);
employeeRouter.delete(
  ENDPOINTS.EMPLOYEES.DELETE_EMPLOYEE_DOC,
  isAuthenticated,
  isAdmin,
  Employees.DeleteController.deleteEmployeeDoc,
);
employeeRouter.delete(
  ENDPOINTS.EMPLOYEES.DELETE_EMPLOYEE_LICENSE,
  isAuthenticated,
  isAdmin,
  Employees.DeleteController.deleteEmployeeLicense,
);
employeeRouter.delete(
  ENDPOINTS.EMPLOYEES.DELETE_EMPLOYEE_VACATION,
  isAuthenticated,
  isAdmin,
  Employees.DeleteController.deleteEmployeeVacation,
);
employeeRouter.delete(
  ENDPOINTS.EMPLOYEES.DELETE_EMPLOYEE_FAMILY_MEMBER,
  isAuthenticated,
  isAdmin,
  Employees.DeleteController.deleteEmployeeFamilyMember,
);
employeeRouter.delete(
  ENDPOINTS.EMPLOYEES.DELETE_LICENSE_TYPE,
  isAuthenticated,
  isAdmin,
  Employees.DeleteController.deleteLicenseType,
);
employeeRouter.delete(
  ENDPOINTS.EMPLOYEES.DELETE_TRAINING_TYPE,
  isAuthenticated,
  isAdmin,
  Employees.DeleteController.deleteTrainingType,
);
